language: python
python:
  - 2.6
  - 2.7

environ:
  - TRAVIS_DATABASE=sqlite SQLALCHEMY_DATABASE_URI="sqlite://:memory:"
  - TRAVIS_DATABASE=postgres SQLALCHEMY_DATABASE_URI="postgresql://postgres:@127.0.0.1/pyfarm"
  - TRAVIS_DATABASE=mysql SQLALCHEMY_DATABASE_URI="mysql://travis:@127.0.0.1/pyfarm"

before_script:
  - if [[ $TRAVIS_DATABASE == "postgres" ]]; then psql -c "create database pyfarm;" -U postgres ; fi
  - if [[ $TRAVIS_DATABASE == "mysql" ]]; then mysql -e "create database pyfarm;" ; fi

install:
  - if [[ $TRAVIS_PYTHON_VERSION != "2.7" ]]; then pip install unittest2 simplejson --use-mirrors ; fi
  - pip install . --use-mirrors

script:
  - pip freeze
  - nosetests -s --verbose tests